### PR TITLE
Set arch flag for everything else too

### PR DESCRIPTION
**Pull request by WardBrian**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Discussed in #33, while this may not be strictly necessary to cross-compile it is probably "playing nice" if we do --

I think this will resolve https://github.com/conda-forge/r-stanheaders-feedstock/issues/34

### CODE REVIEW

**Comment by WardBrian** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
cc @mfansler

**Review by mfansler — CHANGES_REQUESTED** [review]
The selector is working (passes `arch=arm64`), but in the **osx-arm64** build [the logs](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1007782&view=logs&j=15f8dc28-9f6f-5e3a-5b3c-2b169071e5be&t=63fa899e-c160-5185-75c4-c5fd30c90374&l=1547) still report `arch=x86_64`. The other two do change, so I'm wondering what is expected here. Is `arch=arm64` perhaps not the correct way to specify the Apple ARM?

**Comment by WardBrian** [comment]
@mfansler yes, `arm64` is one of the expected names:

https://github.com/RcppCore/RcppParallel/blob/9ff4809439e048fce0db30d46eb626caedfc0b48/src/tbb/build/macos.clang.inc#L82

Weirdly, x86_64 _isn't_? So I'm not sure why it is being set to that of all things

**Review by mfansler — APPROVED** [review]
Oops - slipped off my radar. Given that we pass the correct flags, I see no reason not to do this. If something is wrong with the "x86_64", it isn't currently causing apparent issues. If it ever comes up, at least we have some notes here.

**Pull request merged**
